"""The Slint side of the icon set: one global that maps an app id and a size to its image.

Slint embeds every `@image-url` it compiles into the binary, so the shell needs no file on disk
at run time and no Rust-side loader, and the tile can pick its own art from the id it already
has: AppTile's properties stay what they were for every caller.
"""

HEADER = """\
// GENERATED by design/icons/generate.py from AppColor's table (app_color.slint) and the glyphs in
// design/icons/. Do not edit: change those and run the generator; the kit's tests fail until it
// has been run (src/app_icons.rs).
//
// The pre-rendered app tiles AppTile draws, as images Slint embeds in the binary. `px` is the
// size a tile is drawn at in PHYSICAL pixels, and the art is the smallest at or above it: a 32px
// tile on a 1x display is drawn from the 32px art pixel for pixel, and on a 2x display from the
// 64px art, never a smaller picture stretched.
"""


def _chain(sizes: tuple[int, ...], call: str) -> str:
    arms = [f"px <= {s} ? {call.format(s=s)}" for s in sizes[:-1]]
    return "\n             : ".join(arms + [call.format(s=sizes[-1])])


def _url(path: str) -> str:
    return f'@image-url("../assets/app-icons/{path}")'


def source(ids: list[str], sizes: tuple[int, ...], plate_inks: dict[str, str]) -> str:
    has = "\n            || ".join(f'id == "{i}"' for i in ids)
    out = [HEADER, "export global AppIcons {"]
    out.append("    /// The colour of an unknown app's initial on the neutral plate, in either theme.")
    out.append("    public pure function plate-ink(dark: bool) -> color {")
    out.append(f"        return dark ? {plate_inks['dark']} : {plate_inks['light']};\n    }}\n")
    out.append("    /// Whether there is art for this app id: every app AppColor gives a colour.")
    out.append(f"    public pure function has(id: string) -> bool {{\n        return {has};\n    }}\n")
    out.append("    /// An app's tile at `px` physical pixels.")
    out.append("    public pure function art(id: string, px: int) -> image {")
    out.append(f"        return {_chain(sizes, 'root.art-{s}(id)')};\n    }}\n")
    out.append("    /// The neutral plate: the same squircle and light with no colour and no glyph, for an")
    out.append("    /// app we have no art for (its initial goes on it) and behind a theme's own icon. Pale")
    out.append("    /// in the light theme, a dim graphite in the dark one.")
    out.append("    public pure function plate(px: int, dark: bool) -> image {")
    out.append("        return dark ? root.plate-dark(px) : root.plate-light(px);\n    }\n")
    for theme in ("light", "dark"):
        out.append(f"    pure function plate-{theme}(px: int) -> image {{")
        out.append(f"        return {_chain(sizes, _url('{s}/_plate-' + theme + '.png'))};\n    }}\n")
    out.append("    /// The squircle in white, laid over a tile at low opacity for hover.")
    out.append("    public pure function mask(px: int) -> image {")
    out.append(f"        return {_chain(sizes, _url('{s}/_mask.png'))};\n    }}")
    for s in sizes:
        arms = "\n             : ".join(f'id == "{i}" ? {_url(f"{s}/{i}.png")}' for i in ids)
        out.append(f"\n    pure function art-{s}(id: string) -> image {{")
        out.append(f'        return {arms}\n             : @image-url("");\n    }}')
    out.append("}")
    return "\n".join(out) + "\n"
