//! What a wired link reports about itself, read from text the kernel and the resolver leave.
//!
//! The Network window's ethernet pane showed "—" for Speed, Subnet, Gateway and DNS on a working
//! DHCP interface, because the service read none of them. The readers are here and pure — the
//! file's text in, the value out — so the cases a test machine cannot produce on demand (a
//! virtio NIC's -1, a systemd-resolved stub) are captured strings. The route table's reader,
//! which gives the gateway, is shared with the window (`yantrik_ipc_contracts::route_table`).

use yantrik_ipc_contracts::network::DnsConfig;

/// What the C library resolves through.
pub const RESOLV_CONF: &str = "/etc/resolv.conf";

/// systemd-resolved's list of the servers it forwards to. When `/etc/resolv.conf` points at its
/// local stub, this is where the resolvers a person set actually are.
pub const RESOLVED_UPSTREAM: &str = "/run/systemd/resolve/resolv.conf";

/// The link speed `/sys/class/net/<if>/speed` gives, in Mbit/s.
///
/// The file holds a signed number: a driver that cannot tell writes -1 (virtio does), and a link
/// that is down refuses the read, which arrives here as empty text. Neither is a speed.
pub fn parse_speed(text: &str) -> Option<u32> {
    text.trim().parse::<i64>().ok().filter(|n| *n > 0).and_then(|n| u32::try_from(n).ok())
}

/// The resolvers a `resolv.conf` names, and its search domains.
pub fn parse_resolv_conf(text: &str) -> DnsConfig {
    let mut dns = DnsConfig::default();
    for line in text.lines().map(str::trim) {
        if line.starts_with('#') || line.starts_with(';') {
            continue;
        }
        let mut words = line.split_whitespace();
        match words.next() {
            Some("nameserver") => dns.nameservers.extend(words.next().map(str::to_string)),
            Some("search") => dns.search_domains.extend(words.map(str::to_string)),
            _ => {}
        }
    }
    dns
}

/// Whether every resolver is systemd-resolved's local stub (127.0.0.53, or the 127.0.0.54
/// proxy). "DNS 127.0.0.53" is true and tells a person nothing about where their lookups go.
pub fn is_resolved_stub(dns: &DnsConfig) -> bool {
    !dns.nameservers.is_empty() && dns.nameservers.iter().all(|ns| ns == "127.0.0.53" || ns == "127.0.0.54")
}

/// The machine's resolvers: `/etc/resolv.conf`, or the stub's upstream list when it is a stub
/// and that list names any. `upstream` is `None` when the file is not there to read.
pub fn resolvers(resolv_conf: &str, upstream: Option<&str>) -> DnsConfig {
    let local = parse_resolv_conf(resolv_conf);
    if !is_resolved_stub(&local) {
        return local;
    }
    match upstream.map(parse_resolv_conf) {
        Some(up) if !up.nameservers.is_empty() => DnsConfig {
            nameservers: up.nameservers,
            search_domains: if up.search_domains.is_empty() { local.search_domains } else { up.search_domains },
        },
        // The stub is all there is to report; it is still what the machine resolves through.
        _ => local,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_reported_speed_is_megabits_and_an_unknown_one_is_none() {
        assert_eq!(parse_speed("1000\n"), Some(1000));
        assert_eq!(parse_speed("10000"), Some(10000));
        // virtio, and a link that is down (the read fails and arrives as nothing).
        assert_eq!(parse_speed("-1\n"), None);
        assert_eq!(parse_speed(""), None);
        assert_eq!(parse_speed("0"), None);
        assert_eq!(parse_speed("garbage"), None);
    }

    #[test]
    fn resolv_conf_names_its_servers_and_search_domains() {
        let dns = parse_resolv_conf(
            "# Generated by NetworkManager\nsearch lan home.arpa\nnameserver 192.168.4.1\nnameserver  1.1.1.1\n; old\noptions edns0\n",
        );
        assert_eq!(dns.nameservers, ["192.168.4.1", "1.1.1.1"]);
        assert_eq!(dns.search_domains, ["lan", "home.arpa"]);
        assert!(!is_resolved_stub(&dns));
    }

    #[test]
    fn a_plain_resolv_conf_is_the_answer() {
        let dns = resolvers("nameserver 192.168.4.1\n", Some("nameserver 9.9.9.9\n"));
        assert_eq!(dns.nameservers, ["192.168.4.1"], "the upstream file is read only behind a stub");
    }

    #[test]
    fn behind_the_resolved_stub_the_upstream_servers_are_reported() {
        let stub = "nameserver 127.0.0.53\noptions edns0 trust-ad\nsearch lan\n";
        let up = "nameserver 192.168.4.1\nnameserver 1.1.1.1\n";
        let dns = resolvers(stub, Some(up));
        assert_eq!(dns.nameservers, ["192.168.4.1", "1.1.1.1"]);
        assert_eq!(dns.search_domains, ["lan"], "the stub's search domains stand when upstream has none");
    }

    #[test]
    fn a_stub_with_no_upstream_list_is_still_reported_as_it_is() {
        let stub = "nameserver 127.0.0.53\n";
        assert_eq!(resolvers(stub, None).nameservers, ["127.0.0.53"]);
        assert_eq!(resolvers(stub, Some("# no servers\n")).nameservers, ["127.0.0.53"]);
        assert!(resolvers("", None).nameservers.is_empty());
    }
}
