#!/usr/bin/env python3
"""The image viewer's one job: show the picture you asked for, and say which one it is.

The audit's finding was `open_app name=image-viewer` answering `accepted: true` with no
window, no process, and nothing in `failed_launches` — so the first thing checked here is
a process and a compositor toplevel, and only then what the app says it is showing.

A viewer keeps no store, so contract point 2's witness is the file on disk: the picture's
own IHDR bytes for the dimensions it reports, and its SHA-256 for the promise that turning
it on screen does not rewrite it. `design/images-2026-09-20.md` has the rest.
"""

import binascii
import os
import pathlib
import struct
import sys
import time
import zlib

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import lib  # noqa: E402

ONE_JOB = ("Show the picture you asked for: name it, report what the file actually is, and "
           "move through the folder it sits in.")

APP = "image-viewer"
APP_BIN = "/opt/yantrik/bin/yantrik-image-viewer"
PICTURES = pathlib.Path.home() / "Pictures"
FIXTURES = pathlib.Path(__file__).resolve().parent.parent / "fixtures"

# Distinct sizes, so "1920 x 1200" cannot be a coincidence shared by two files.
GENERATED = [("aurora", 640, 400), ("first-light", 480, 300), ("ocean", 800, 500)]


def png_dimensions(path):
    """Width and height straight out of the file's IHDR, with no library in between."""
    head = pathlib.Path(path).read_bytes()[:24]
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    return struct.unpack(">II", head[16:24])


def _chunk(kind, payload):
    return (struct.pack(">I", len(payload)) + kind + payload
            + struct.pack(">I", binascii.crc32(kind + payload) & 0xFFFFFFFF))


def write_png(path, width, height, tint):
    """A real 8-bit RGB PNG, written with the standard library.

    The suite prefers the repo's own wallpapers when `run-on-vm.sh` has staged them into
    `fixtures/`, because those are the pictures the app was checked against by hand. This
    exists so the probe still works when run straight on a machine with no fixtures: it is
    a genuine PNG of a known size, which is what the dimension check needs.
    """
    rows = bytearray()
    for y in range(height):
        rows.append(0)  # filter: none
        for x in range(width):
            rows += bytes(((x * 255) // width, (y * 255) // height, tint))
    data = (b"\x89PNG\r\n\x1a\n"
            + _chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
            + _chunk(b"IDAT", zlib.compress(bytes(rows), 6))
            + _chunk(b"IEND", b""))
    pathlib.Path(path).write_bytes(data)


def stage(probe):
    """Three pictures and one file that is named like one but is not. Returns the paths."""
    PICTURES.mkdir(exist_ok=True)
    fixtures = sorted(FIXTURES.glob("*.png")) if FIXTURES.is_dir() else []
    pictures = []
    if len(fixtures) >= 3:
        probe.note("picture_source", "fixtures staged from the repo: %s"
                   % ", ".join(f.name for f in fixtures[:3]))
        for index, source in enumerate(fixtures[:3], start=1):
            target = PICTURES / ("conformance-%d-%s" % (index, source.name))
            target.write_bytes(source.read_bytes())
            pictures.append(target)
    else:
        probe.note("picture_source",
                   "no fixtures at %s; three PNGs generated by the probe" % FIXTURES)
        for index, (name, width, height) in enumerate(GENERATED, start=1):
            target = PICTURES / ("conformance-%d-%s.png" % (index, name))
            write_png(target, width, height, index * 60)
            pictures.append(target)
    not_a_picture = PICTURES / "conformance-notes.png"
    not_a_picture.write_text("this is text, not an image\n")
    return pictures, not_a_picture


with lib.Probe(APP, ONE_JOB) as probe:
    probe.note("processes_before", lib.running(APP_BIN))
    probe.note("windows_before", lib.toplevels())

    pics_dir = lib.preserved(PICTURES)
    with pics_dir:
        probe.note("pictures_before", pics_dir.listing())

        # A viewer left over from an earlier run holds an earlier folder; start cold.
        probe.note("closed_before_starting", lib.kill_app(APP_BIN))
        pictures, not_a_picture = stage(probe)
        probe.note("staged", [p.name for p in pictures] + [not_a_picture.name])

        # ── 1. It opens ──────────────────────────────────────────────────────
        opened = lib.open_app(APP, expect_process=APP_BIN, window_words=("image", "images"),
                              timeout=45)
        probe.check(
            "it opens: a process exists and the compositor has its window",
            bool(opened["processes"]) and bool(opened["windows"]) and opened["surface_up"],
            contract=1, evidence=opened)
        probe.check(
            "a launch that worked adds nothing to the shell's failed_launches",
            opened["new_failed_launches_for_this_app"] == [],
            contract=1, evidence={"added_by_this_launch": opened["new_failed_launches"],
                                  "whole_list": opened["failed_launches"]})

        # ── 2. It does its one job, checked against the file, not the answer ─
        first = pictures[0]
        result = lib.act(APP, "open", path=str(first))
        lib.wait_for(lambda: lib.state(APP).get("path") == str(first), timeout=15)
        view = lib.state(APP)
        real = png_dimensions(first)
        reported = "".join(ch if ch.isdigit() else " " for ch in str(view.get("dimensions"))).split()
        probe.check(
            "open shows the picture that was asked for, and not a different one",
            view.get("path") == str(first) and view.get("file") == first.name,
            contract=2, evidence={"asked_for": str(first), "path": view.get("path"),
                                  "file": view.get("file"), "action_result": result.get("result"),
                                  "refused": result.get("refused")})
        probe.check(
            "the dimensions it reports are the ones in the file's own header",
            real is not None and reported == [str(real[0]), str(real[1])],
            contract=2, evidence={"reported": view.get("dimensions"),
                                  "in_the_file": "%d x %d" % real if real else None,
                                  "file_size": view.get("file_size"), "format": view.get("format"),
                                  "on_disk_bytes": first.stat().st_size})
        probe.check(
            "it knows where the picture sits in its folder",
            view.get("position") == 1 and view.get("of") == 4,
            contract=2, evidence={"position": view.get("position"), "of": view.get("of"),
                                  "folder": view.get("folder"),
                                  "on_disk": sorted(p.name for p in PICTURES.iterdir())})

        # ── 2. Moving through the folder ─────────────────────────────────────
        lib.act(APP, "next")
        time.sleep(1)
        after_next = lib.state(APP)
        lib.act(APP, "previous")
        time.sleep(1)
        after_previous = lib.state(APP)
        probe.check(
            "next moves to the following picture and previous comes back",
            after_next.get("file") == pictures[1].name
            and after_previous.get("file") == first.name,
            contract=2, evidence={"after_next": after_next.get("file"),
                                  "after_previous": after_previous.get("file"),
                                  "folder_in_name_order": after_next.get("folder")})

        # ── 3. Actions report what happened ──────────────────────────────────
        before_hash = lib.sha256(first)
        rotation_before = lib.state(APP).get("rotation") or 0
        turned = lib.act(APP, "rotate", direction="right")
        time.sleep(1)
        rotation_after = lib.state(APP).get("rotation")
        after_hash = lib.sha256(first)
        probe.check(
            "rotate turns the picture on screen and says the file is unchanged",
            (turned.get("result") or {}).get("file_unchanged") is True
            and rotation_after == (int(rotation_before) + 90) % 360
            and before_hash == after_hash,
            contract=3, evidence={"action_result": turned.get("result"),
                                  "rotation_before": rotation_before,
                                  "rotation_after": rotation_after,
                                  "sha256_before": before_hash, "sha256_after": after_hash})

        # ── 4. Failure is said twice ─────────────────────────────────────────
        bad = lib.act(APP, "open", path=str(not_a_picture))
        time.sleep(2)
        bad_view = lib.state(APP)
        probe.check(
            "a file that is not a picture is named on screen, not left blank",
            not_a_picture.name in str(bad_view.get("notice"))
            or not_a_picture.name in str(bad.get("refused")),
            contract=4, evidence={"notice": bad_view.get("notice"),
                                  "refused": bad.get("refused"),
                                  "action_result": bad.get("result"),
                                  "file": bad_view.get("file")})

        missing = PICTURES / "conformance-nothing-here.png"
        gone = lib.act(APP, "open", path=str(missing))
        time.sleep(1)
        gone_notice = lib.state(APP).get("notice") or ""
        said = str(gone.get("refused") or "") + " " + str(gone.get("result") or "")
        probe.check(
            "a path that is not there is refused by name",
            str(missing) in said or str(missing) in gone_notice,
            contract=4, evidence={"asked_for": str(missing), "refused": gone.get("refused"),
                                  "action_result": gone.get("result"), "notice": gone_notice})

        # ── 5. It takes work from outside ────────────────────────────────────
        lib.act(APP, "open", path=str(first))
        time.sleep(1)
        processes_before = lib.running(APP_BIN)
        handover = lib.run_and_wait([APP_BIN, str(pictures[2])], timeout=40)
        lib.wait_for(lambda: lib.state(APP).get("file") == pictures[2].name, timeout=15)
        processes_after = lib.running(APP_BIN)
        probe.check(
            "a second launch hands its file to the open window instead of opening another",
            len(processes_after) == len(processes_before) == 1
            and lib.state(APP).get("file") == pictures[2].name,
            contract=5, evidence={"processes_before": processes_before,
                                  "processes_after": processes_after,
                                  "showing": lib.state(APP).get("file"),
                                  "second_launch": handover,
                                  "windows": lib.toplevels()})

        # ── 6. It survives a restart ─────────────────────────────────────────
        # A viewer holds nothing that could outlive it, so this is the weaker half of
        # point 6: it comes back, takes the path it is given, and does its job again.
        killed = lib.kill_app(APP_BIN)
        lib.spawn([APP_BIN, str(pictures[1])])
        lib.wait_for(lambda: lib.surface_up(APP), timeout=45)
        lib.wait_for(lambda: lib.state(APP).get("file") == pictures[1].name, timeout=15)
        restarted = lib.state(APP)
        probe.check(
            "killed and started again with a path, it opens on that picture",
            bool(lib.running(APP_BIN)) and restarted.get("file") == pictures[1].name
            and lib.has_window("image"),
            contract=6, evidence={"killed": killed, "processes": lib.running(APP_BIN),
                                  "file": restarted.get("file"),
                                  "position": "%s of %s" % (restarted.get("position"),
                                                            restarted.get("of")),
                                  "windows": lib.toplevels(),
                                  "note": "a viewer keeps no state, so this is restart-and-"
                                          "still-works rather than state-survived-restart"})

        # ── Put the machine back ─────────────────────────────────────────────
        lib.kill_app(APP_BIN)

    probe.note("pictures_after", pics_dir.listing(pics_dir.after))
    probe.check(
        "~/Pictures is left exactly as it was found",
        not pics_dir.differences(),
        contract="leave-as-found",
        evidence={"before": pics_dir.listing(), "after": pics_dir.listing(pics_dir.after),
                  "differences": pics_dir.differences() or "none"})

    leftover = lib.running(APP_BIN)
    probe.note("processes_after", leftover)
    probe.note("windows_after", lib.toplevels())
    probe.check(
        "no image viewer is left running that was not running before",
        len(leftover) <= len(probe.notes["processes_before"]),
        contract="leave-as-found",
        evidence={"before": probe.notes["processes_before"], "after": leftover,
                  "note": "the probe closes the viewer it opened; a viewer that was already "
                          "running is killed by the restart check and not put back"})
